#!/usr/bin/env python3

import subprocess
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Optional, cast

import dateparser
import humanfriendly
import typer

app = typer.Typer()

SUBTITLES_OPTIONS = 'Fontname=Roboto,Fontsize=24,PrimaryColour=&H00ffffff,BackColour=&H00000000,OutlineColour=&H00000000,Bold=1,Italic=0,Alignment=2,BorderStyle=1,Outline=0.4,Shadow=0.4,MarginL=20,MarginR=20,MarginV=10'
X265_HQ_PARAMS = "bframes=8:psy-rd=1:aq-mode=3:aq-strength=0.8:deblock=1,1"


def extract_duration(input_path: Path) -> float:
    return float(
        subprocess.check_output(
            [
                'ffprobe',
                '-v',
                'error',
                '-show_entries',
                'format=duration',
                '-of',
                'default=noprint_wrappers=1:nokey=1',
                input_path,
            ]
        )
    )


def time_to_seconds(timestamp: str) -> Optional[float]:
    if not timestamp:
        return None
    delta = cast(datetime, dateparser.parse(timestamp)) - cast(
        datetime, dateparser.parse('00:00:00')
    )
    return delta.total_seconds()


def calculate_duration(input_path: Path, time_from: str, time_to: str) -> float:
    parsed_from = time_to_seconds(time_from)
    parsed_to = time_to_seconds(time_to)
    if parsed_from or parsed_from == 0:
        if parsed_to:
            return parsed_to - parsed_from
        return extract_duration(input_path) - parsed_from
    if parsed_to:
        return parsed_to
    return extract_duration(input_path)


def call_ffmpeg(args: list) -> None:
    args = ['ffmpeg', '-hide_banner'] + [str(i) for i in args]
    print(' '.join(args))
    subprocess.check_call(args)


class Preset(str, Enum):
    slow = 'slow'
    medium = 'medium'
    fast = 'fast'
    veryfast = 'veryfast'


class X265Tune(str, Enum):
    animation = 'animation'
    grain = 'grain'


@app.command()
def x265hq(
    input_path: Path,
    output_path: Path,
    crf: float,
    preset: Preset = typer.Option(Preset.slow, '-p', case_sensitive=False),
    time_from: str = typer.Option('', '-from'),
    time_to: str = typer.Option('', '-to'),
    video_filter: str = typer.Option('', '-vf'),
    tune: Optional[X265Tune] = typer.Option(None, '-t', case_sensitive=False),
) -> None:
    ffmpeg_args = []
    if time_from:
        ffmpeg_args += ['-ss', time_from]
    if time_to:
        ffmpeg_args += ['-to', time_to]
    ffmpeg_args += ['-i', str(input_path)]

    if video_filter:
        ffmpeg_args += ['-vf', video_filter]
    ffmpeg_args += [
        '-c:v', 'libx265', '-crf',
        str(crf), '-preset', preset.name, '-pix_fmt', 'yuv420p10le', '-x265-params', X265_HQ_PARAMS,
        '-c:s', 'copy',
        '-c:a', 'aac', '-b:a', '128k'
        '-map', '0:0',
        '-map_metadata', '0', '-map_chapters', '0',
        '-movflags', 'use_metadata_tags',
    ]  # fmt: off
    if tune:
        ffmpeg_args += ['-tune', tune.name]
    call_ffmpeg(ffmpeg_args + [str(output_path)])


@app.command()
def ix265hq(
    input_path: Path,
    output_path: Path,
    crf: float,
    fps: float,
    video_filter: str = typer.Option('', '-vf'),
    preset: Preset = typer.Option(Preset.slow, '-p', case_sensitive=False),
    tune: Optional[X265Tune] = typer.Option(None, '-t', case_sensitive=False),
) -> None:
    ffmpeg_args = [
        '-framerate', str(fps),
        '-f', 'image2', '-i', str(input_path)
    ]  # fmt: off
    if video_filter:
        ffmpeg_args += ['-vf', video_filter]
    ffmpeg_args += [
        '-c:v', 'libx265', '-crf',
        str(crf), '-preset', preset.name, '-pix_fmt', 'yuv420p10le', '-x265-params', X265_HQ_PARAMS,
        '-an'
    ]  # fmt: off
    if tune:
        ffmpeg_args += ['-tune', tune.name]
    call_ffmpeg(ffmpeg_args + [str(output_path)])


@app.command()
def x264(
    input_path: Path,
    output_path: Path,
    crf: float,
    preset: Preset = typer.Option(Preset.slow, '-p', case_sensitive=False),
    time_from: str = typer.Option('', '-from'),
    time_to: str = typer.Option('', '-to'),
    video_filter: str = typer.Option('', '-vf'),
    with_audio: bool = typer.Option(False, '-audio/-no-audio'),
    audio_filter: str = typer.Option('', '-af'),
    subtitles_path: Path = typer.Option(None, '-subs'),
    tune: Optional[X265Tune] = typer.Option(None, '-t', case_sensitive=False),
) -> None:
    ffmpeg_args = []
    if time_from:
        ffmpeg_args += ['-ss', time_from]
    if time_to:
        ffmpeg_args += ['-to', time_to]
    ffmpeg_args += ['-i', str(input_path)]

    if subtitles_path:
        if video_filter:
            video_filter += ','
        video_filter += f'subtitles={str(subtitles_path)}:force_style=\'{SUBTITLES_OPTIONS}\''
    if video_filter:
        ffmpeg_args += ['-vf', video_filter]
    if audio_filter:
        ffmpeg_args += ['-af', audio_filter]
    ffmpeg_args += [
        '-c:v', 'libx264', '-crf',
        str(crf), '-preset', preset.name,
        # '-profile:v', 'baseline',
        '-profile:v', 'high',
        '-pix_fmt', 'yuv420p',
        '-sn',
        '-map_metadata', '-1', '-map_chapters', '-1',
    ]  # fmt: off
    # ffmpeg_args += ['-c:a', 'aac', '-ac', '2', '-b:a', '128K'] if with_audio else ['-an']
    # ffmpeg_args += ['-c:a', 'aac', '-ac', '1', '-b:a', '96K'] if with_audio else ['-an']
    ffmpeg_args += ['-c:a', 'copy'] if with_audio else ['-an']
    if tune:
        ffmpeg_args += ['-tune', tune.name]
    call_ffmpeg(ffmpeg_args + [str(output_path)])


@app.command()
def ix264(
    input_path: Path,
    output_path: Path,
    crf: float,
    fps: float,
    video_filter: str = typer.Option('', '-vf'),
    preset: Preset = typer.Option(Preset.slow, '-p', case_sensitive=False),
    audio: Optional[Path] = typer.Option(None),
    tune: Optional[X265Tune] = typer.Option(None, '-t', case_sensitive=False),
) -> None:
    ffmpeg_args = [
        '-framerate', str(fps),
        '-f', 'image2', '-i', str(input_path)
    ]  # fmt: off
    if audio:
        ffmpeg_args += ['-i', str(audio)]
    if video_filter:
        ffmpeg_args += ['-vf', video_filter]
    ffmpeg_args += [
        '-c:v', 'libx264', '-crf',
        str(crf), '-preset', preset.name,
        '-profile:v', 'baseline',
        '-pix_fmt', 'yuv420p',
        '-sn',
    ]  # fmt: off
    if tune:
        ffmpeg_args += ['-tune', tune.name]
    if audio:
        ffmpeg_args += ['-c:a', 'copy']
        # ffmpeg_args += ['-c:a', 'aac', '-ac', '2', '-b:a', '128K']
    else:
        ffmpeg_args += ['-an']

    call_ffmpeg(ffmpeg_args + [str(output_path)])


@app.command()
def gif(
    input_path: Path,
    output_path: Path,
    speed: float = typer.Option(1.0, '-speed'),
    time_from: str = typer.Option('', '-from'),
    time_to: str = typer.Option('', '-to'),
    video_filter: str = typer.Option('', '-vf'),
) -> None:
    ffmpeg_args = []
    if time_from:
        ffmpeg_args += ['-ss', time_from]
    if time_to:
        ffmpeg_args += ['-to', time_to]
    ffmpeg_args += ['-i', str(input_path)]

    if video_filter:
        video_filter += ','
    video_filter += f'setpts={1/speed}*PTS,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse'
    ffmpeg_args += ['-vf', video_filter]

    ffmpeg_args += [
        '-c:v', 'gif',
        '-map_metadata', '-1', '-map_chapters', '-1',
    ]  # fmt: off

    call_ffmpeg(ffmpeg_args + [str(output_path)])


@app.command()
def images(
    input_path: Path,
    output_path: Path,
    time_from: str = typer.Option('', '-from'),
    time_to: str = typer.Option('', '-to'),
    video_filter: str = typer.Option('', '-vf'),
) -> None:
    ffmpeg_args = []
    if time_from:
        ffmpeg_args += ['-ss', time_from]
    if time_to:
        ffmpeg_args += ['-to', time_to]
    ffmpeg_args += ['-i', str(input_path)]

    if video_filter:
        ffmpeg_args += ['-vf', video_filter]

    if output_path.suffix.lower() in ('.jpg', '.jpeg'):
        ffmpeg_args += ['-pix_fmt', 'yuvj444p']
    ffmpeg_args += ['-qscale:v', '2', str(output_path)]
    output_path.parent.mkdir(exist_ok=True)
    call_ffmpeg(ffmpeg_args)


@app.command()
def webm(
    input_path: Path,
    output_path: Path,
    output_size: str,
    time_from: str = typer.Option('', '-from'),
    time_to: str = typer.Option('', '-to'),
    video_filter: str = typer.Option('', '-vf'),
    with_audio: bool = typer.Option(False, '-audio/-no-audio'),
    subtitles_path: Path = typer.Option(None, '-subs'),
    fps: str = typer.Option('', '-fps'),
    bitexact: bool = typer.Option(False, '-bitexact'),
) -> None:
    size_bytes = humanfriendly.parse_size(output_size)
    duration = calculate_duration(input_path, time_from, time_to)
    bps = int(8.0 * size_bytes / duration)
    print(f'Duration: {duration}\tVideo Bitrate: {bps}')

    ffmpeg_args = []
    if time_from:
        ffmpeg_args += ['-ss', time_from]
    if time_to:
        ffmpeg_args += ['-to', time_to]
    ffmpeg_args += ['-i', str(input_path)]

    if subtitles_path:
        if video_filter:
            video_filter += ','
        video_filter += f'subtitles={str(subtitles_path)}:force_style=\'{SUBTITLES_OPTIONS}\''
    if video_filter:
        ffmpeg_args += ['-vf', video_filter]
    ffmpeg_args += [
        '-c:v', 'libvpx', '-b:v', str(bps),
        # '-pix_fmt', 'yuva420p',
        '-deadline', 'best', '-sn',
        '-map_metadata', '-1', '-map_chapters', '-1', '-map_metadata:s:v', '-1',
    ]  # fmt: off
    if input_path.suffix.lower() == '.gif':
        ffmpeg_args += ['-auto-alt-ref', '0']
    if fps:
        ffmpeg_args += ['-r', fps]
    bitexact_params = ['-bitexact'] if bitexact else []
    call_ffmpeg(
        ffmpeg_args + ['-an', '-pass', '1'] + bitexact_params + ['-y', '-f', 'webm', '/dev/null']
    )
    ffmpeg_args += ['-c:a', 'libvorbis', '-ac', '2', '-b:a', '80K'] if with_audio else ['-an']
    call_ffmpeg(ffmpeg_args + ['-pass', '2'] + bitexact_params + ['-y', str(output_path)])


@app.command()
def vp9webm(
    input_path: Path,
    output_path: Path,
    output_size: str,
    time_from: str = typer.Option('', '-from'),
    time_to: str = typer.Option('', '-to'),
    video_filter: str = typer.Option('', '-vf'),
    with_audio: bool = typer.Option(False, '-audio/-no-audio'),
    subtitles_path: Path = typer.Option(None, '-subs'),
    bitexact: bool = typer.Option(False, '-bitexact'),
) -> None:
    size_bytes = humanfriendly.parse_size(output_size)
    duration = calculate_duration(input_path, time_from, time_to)
    bps = int(8.0 * size_bytes / duration)
    print(f'Duration: {duration}\tVideo Bitrate: {bps}')

    ffmpeg_args = []
    if time_from:
        ffmpeg_args += ['-ss', time_from]
    if time_to:
        ffmpeg_args += ['-to', time_to]
    ffmpeg_args += ['-i', str(input_path)]

    if subtitles_path:
        if video_filter:
            video_filter += ','
        video_filter += f'subtitles={str(subtitles_path)}:force_style=\'{SUBTITLES_OPTIONS}\''
    if video_filter:
        ffmpeg_args += ['-vf', video_filter]
    ffmpeg_args += [
        '-c:v', 'libvpx-vp9', '-b:v', str(bps),
        '-row-mt', '1',
        '-threads', '4',
        '-cpu-used', '2',
        '-pix_fmt', 'yuv420p',
        #'-auto-alt-ref', '0',
        '-deadline', 'good', '-sn',
        '-map_metadata', '-1', '-map_chapters', '-1', '-map_metadata:s:v', '-1',
    ]  # fmt: off
    bitexact_params = ['-bitexact'] if bitexact else []
    call_ffmpeg(
        ffmpeg_args + ['-an', '-pass', '1'] + bitexact_params + ['-y', '-f', 'webm', '/dev/null']
    )
    ffmpeg_args += ['-c:a', 'libvorbis', '-ac', '2', '-b:a', '80K'] if with_audio else ['-an']
    call_ffmpeg(ffmpeg_args + ['-pass', '2'] + bitexact_params + ['-y', str(output_path)])


@app.command()
def iwebm(
    input_path: Path,
    output_path: Path,
    output_size: str,
    fps: float,
    video_filter: str = typer.Option('', '-vf'),
    audio_path: Path = typer.Option(None, '-audio'),
    bitexact: bool = typer.Option(False, '-bitexact'),
) -> None:
    size_bytes = humanfriendly.parse_size(output_size)
    frames_count = len([1 for i in input_path.parent.iterdir() if i.is_file()])
    bps = int(8.0 * size_bytes * fps / frames_count)
    ffmpeg_args = [
        '-framerate',
        str(fps), '-f', 'image2', '-i',
        str(input_path)
    ]  # fmt: off
    if audio_path:
        ffmpeg_args += ['-i', str(audio_path)]
    if video_filter:
        ffmpeg_args += ['-vf', video_filter]
    ffmpeg_args += [
        '-auto-alt-ref', '0',
        '-c:v', 'libvpx', '-b:v',
        str(bps), '-deadline', 'best', '-sn',
        '-map_metadata', '-1', '-map_chapters', '-1', '-map_metadata:s:v', '-1',
    ]  # fmt: off
    bitexact_params = ['-bitexact'] if bitexact else []
    call_ffmpeg(
        ffmpeg_args + ['-an', '-pass', '1'] + bitexact_params + ['-y', '-f', 'webm', '/dev/null']
    )
    if audio_path:
        ffmpeg_args += ['-c:a', 'libvorbis', '-b:a', '128K']
    call_ffmpeg(ffmpeg_args + ['-pass', '2'] + bitexact_params + ['-y', str(output_path)])


@app.command()
def ivp9webm(
    input_path: Path,
    output_path: Path,
    output_size: str,
    fps: float,
    video_filter: str = typer.Option('', '-vf'),
    audio_path: Path = typer.Option(None, '-audio'),
    bitexact: bool = typer.Option(False, '-bitexact'),
) -> None:
    size_bytes = humanfriendly.parse_size(output_size)
    frames_count = len([1 for i in input_path.parent.iterdir() if i.is_file()])
    bps = int(8.0 * size_bytes * fps / frames_count)
    ffmpeg_args = [
        '-framerate', str(fps),
        '-f', 'image2', '-i', str(input_path)
    ]  # fmt: off
    if audio_path:
        ffmpeg_args += ['-i', str(audio_path)]
    if video_filter:
        ffmpeg_args += ['-vf', video_filter]
    ffmpeg_args += [
        '-c:v', 'libvpx-vp9', '-b:v', str(bps),
        '-row-mt', '1',
        '-threads', '4',
        '-cpu-used', '2',
        '-pix_fmt', 'yuv444p', #'-auto-alt-ref', '0',
        '-deadline', 'good', '-sn',
        '-map_metadata', '-1', '-map_chapters', '-1', '-map_metadata:s:v', '-1',
    ]  # fmt: off
    bitexact_params = ['-bitexact'] if bitexact else []
    call_ffmpeg(
        ffmpeg_args + ['-an', '-pass', '1'] + bitexact_params + ['-y', '-f', 'webm', '/dev/null']
    )
    if audio_path:
        ffmpeg_args += ['-c:a', 'libvorbis', '-b:a', '128K']
    call_ffmpeg(ffmpeg_args + ['-pass', '2'] + bitexact_params + ['-y', str(output_path)])


@app.command()
def igif(
    input_path: Path,
    output_path: Path,
    fps: float,
    speed: float = typer.Option(1.0, '-speed'),
    video_filter: str = typer.Option('', '-vf'),
) -> None:
    ffmpeg_args = [
        '-framerate',
        str(fps), '-f', 'image2', '-i',
        str(input_path)
    ]  # fmt: off

    if video_filter:
        ffmpeg_args += ['-vf', video_filter]
    video_filter += f'setpts={1/speed}*PTS,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse'
    ffmpeg_args += ['-vf', video_filter]

    ffmpeg_args += [
        '-c:v', 'gif',
        '-map_metadata', '-1', '-map_chapters', '-1',
    ]  # fmt: off

    call_ffmpeg(ffmpeg_args + [str(output_path)])


@app.command()
def copy(
    input_path: Path,
    output_path: Path,
    time_from: str = typer.Option('', '-from'),
    time_to: str = typer.Option('', '-to'),
) -> None:
    ffmpeg_args = []
    if time_from:
        ffmpeg_args += ['-ss', time_from]
    if time_to:
        ffmpeg_args += ['-to', time_to]

    ffmpeg_args += [
        '-i', str(input_path),
        '-map', '0',
        '-c:v', 'copy',
        '-c:a', 'copy',
        '-c:s', 'copy',
    ]  # fmt: off
    call_ffmpeg(ffmpeg_args + ['-y', str(output_path)])


if __name__ == "__main__":
    app()
