[project]
name = "dotfiles"
version = "1.0.0"
requires-python = ">= 3.10"
readme = "README.md"
license = "MIT"

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
