#!/bin/bash

setxkbmap -option 'grp:alt_shift_toggle' -option 'ctrl:nocaps'
(sleep 3; feh --bg-fill ~/Pictures/wallpaper.png) &
gnome-settings-daemon &
nm-applet &
x-terminal-emulator &
kupfer --no-splash &
i3
