#!/bin/bash

type feh > /dev/null 2>&1 && feh --bg-fill ~/Pictures/wallpaper.png
type autocutsel > /dev/null 2>&1 && autocutsel -fork
type autocutsel > /dev/null 2>&1 && autocutsel -selection PRIMARY -fork
type alttab > /dev/null 2>&1 && alttab -w 1 -d 1 -sc 1 -s 2 -bg black -fg white -frame "#00AAFF" -t 160x140 &
type nm-applet > /dev/null 2>&1 && nm-applet &
exec i3
