[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx
# Set up the prompt

#setopt histignorealldups sharehistory

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=$HOME/.zsh_history

# Use modern completion system
autoload -Uz compinit && compinit -i

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
# ignore case
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

# oz custom starts here

# simple power prompt
autoload -Uz vcs_info
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:*' get-revision true
zstyle ':vcs_info:*' use-simple true
zstyle ':vcs_info:*' unstagedstr ' %F{red}✗ %f'
zstyle ':vcs_info:*' formats '%f%u%F{green}[%b]'
zstyle ':vcs_info:*' actionformats ' %F{blue}%b%f %F{white}%.7i%f +%a%u'
zstyle ':vcs_info:git*+set-message:*' hooks git-status
function precmd() {
	vcs_info
	PS1="$($HOME/.config/zprompt)"
}
setopt prompt_subst
RPROMPT='${vcs_info_msg_0_}'

# auto cd
setopt AUTO_CD

# spell check
setopt CORRECT
export EDITOR="vim"
# ls in color
if [ -x /usr/bin/dircolors ]; then
	alias ls='ls --color=auto --group-directories-first'
	alias dir='dir --color=auto'
	alias vdir='vdir --color=auto'
	alias grep='grep --color=auto'
	alias fgrep='fgrep --color=auto'
	alias egrep='egrep --color=auto'
fi

# ls aliases
alias ll='ls -lFhX --time-style=long-iso'
alias la='ls -A'
alias l='ls -CF'

# command-not found module
if [[ -s '/etc/zsh_command_not_found' ]]; then
	source '/etc/zsh_command_not_found'
fi

source $HOME/.zsh/syntaxhl/zsh-syntax-highlighting.zsh

# Home and End
bindkey "\e[H" beginning-of-line
bindkey "\e[F" end-of-line
# Ctrl-Left and Ctrl-Right
bindkey "\e[1;5D" backward-word
bindkey "\e[1;5C" forward-word
# Insert and Delete
bindkey "\e[2~" overwrite-mode
bindkey "\e[3~" delete-char
# Pageup and Pagedown
bindkey "\e[5~" beginning-of-buffer-or-history
bindkey "\e[6~"	end-of-buffer-or-history

# Colored man
man() {
    env LESS_TERMCAP_mb=$'\E[01;31m' \
    LESS_TERMCAP_md=$'\E[01;38;5;74m' \
    LESS_TERMCAP_me=$'\E[0m' \
    LESS_TERMCAP_se=$'\E[0m' \
    LESS_TERMCAP_so=$'\E[38;5;246m' \
    LESS_TERMCAP_ue=$'\E[0m' \
    LESS_TERMCAP_us=$'\E[04;38;5;146m' \
    man "$@"
}
export TERM=xterm-256color
setopt PATH_DIRS
setopt APPEND_HISTORY

source $HOME/.zsh/extra.zsh
source $HOME/.profile
