[[ -n "$ZPROFILE_LOADED" ]] && return || export ZPROFILE_LOADED=1

export EDITOR="nvim"
export GTAGSLABEL=pygments
export QT_QPA_PLATFORMTHEME=gtk2
export DOTFILES_ROOT="$HOME/.dotfiles"

export ANDROID_SDK_ROOT="/opt/studio-android-sdk"
export ANDROID_NDK_ROOT="/opt/studio-android-sdk/ndk"
export ANDROID_HOME="$ANDROID_SDK_ROOT"
export ANDROID_NDK_HOME="$ANDROID_NDK_ROOT"

# PATH
ANDROID_PATHS="$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/tools/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/emulator"
export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$DOTFILES_ROOT/dotfiles/scripts:$HOME/Code/scripts:$ANDROID_PATHS:$PATH"

# SSH Agent
if [ ! -z "$XDG_RUNTIME_DIR" ]; then
	SSH_AGENT_ENV_PATH="${XDG_RUNTIME_DIR}/ssh-agent-${USER}.env"
else
	SSH_AGENT_ENV_PATH="/tmp/ssh-agent-${USER}.env"
fi

if ! pgrep -u "$USER" ssh-agent > /dev/null; then
	ssh-agent > "$SSH_AGENT_ENV_PATH"
	chmod 600 "$SSH_AGENT_ENV_PATH"
fi
if [ -z "$SSH_AUTH_SOCK" ]; then
	source "$SSH_AGENT_ENV_PATH" > /dev/null
fi

[[ -f $HOME/.profile ]] && source $HOME/.profile
