export ANDROID_SDK_ROOT="/opt/studio-android-sdk"
export ANDROID_HOME="$ANDROID_SDK_ROOT"

export ANDROID_NDK_ROOT="/opt/studio-android-sdk/ndk"
export ANDROID_NDK_HOME="$ANDROID_NDK_ROOT"

export EDITOR="nvim"
export GTAGSLABEL=pygments
export QT_QPA_PLATFORMTHEME=gtk2
export PYTHONDONTWRITEBYTECODE=1
export DOTFILES_ROOT="$HOME/.dotfiles"
export XDG_CACHE_HOME="$XDG_RUNTIME_DIR/cache"

ANDROID_PATHS="$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/tools/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/emulator"

if [[ ":$PATH:" != *":$ANDROID_PATHS:"* ]]; then
	export PATH="$HOME/.local/bin:$DOTFILES_ROOT/dotfiles/scripts:$ANDROID_PATHS:$PATH"
fi
