[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && which startx > /dev/null && exec startx

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "$HOME/.cache/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "$HOME/.cache/p10k-instant-prompt-${(%):-%n}.zsh"
fi

setopt histignorealldups sharehistory
bindkey -e
set -o vi

HISTSIZE=100000
SAVEHIST=100000
HISTFILE=$HOME/.zsh_history
setopt APPEND_HISTORY
setopt PATH_DIRS
setopt AUTO_CD
setopt CORRECT
setopt PROMPT_SUBST
eval "$(/usr/bin/dircolors -b)"

fpath=($DOTFILES_ROOT/dotfiles/zsh/completions $fpath)
autoload -Uz compinit && compinit -i

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*:functions' ignored-patterns '_*'
zstyle ':completion:*:messages' format '%F{purple}-- %d --%f'
zstyle ':completion:*:descriptions' format '%F{yellow}-- %d --%f'
zstyle ':completion:*:corrections' format '%F{green}-- %d (errors: %e) --%f'
zstyle ':completion:*:warnings' format '%F{red}-- No matches for:%f %d --'
# Ignore case
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,cmd'

autoload -U url-quote-magic bracketed-paste-magic
zle -N self-insert url-quote-magic
zle -N bracketed-paste bracketed-paste-magic

up-line-or-local-history() {
  zle set-local-history 1
  zle up-line-or-history
  zle set-local-history 0
}
down-line-or-local-history() {
  zle set-local-history 1
  zle down-line-or-history
  zle set-local-history 0
}

# Arrows local history
bindkey "^[OA" up-line-or-local-history
bindkey "^[OB" down-line-or-local-history
zle -N up-line-or-local-history
zle -N down-line-or-local-history

# Home and End
bindkey "\e[1~" beginning-of-line
bindkey "\e[4~" end-of-line
bindkey "\e[H" beginning-of-line
bindkey "\e[F" end-of-line
bindkey "${terminfo[khome]}" beginning-of-line
bindkey "${terminfo[kend]}" end-of-line
# Insert and Delete
bindkey "${terminfo[kich1]}" overwrite-mode
bindkey "${terminfo[kdch1]}" delete-char
# Pageup and Pagedown
bindkey "${terminfo[kpp]}" beginning-of-buffer-or-history
bindkey "${terminfo[knp]}" end-of-buffer-or-history
# Ctrl-Left and Ctrl-Right
bindkey "\e[5C" forward-word
bindkey "\e[5D" backward-word
bindkey "\e\e[C" forward-word
bindkey "\e\e[D" backward-word
bindkey "\e[1;5C" forward-word
bindkey "\e[1;5D" backward-word
bindkey -M vicmd '^[[1;5C' forward-word
bindkey -M vicmd '^[[1;5D' backward-word
bindkey -M viins '^[[1;5C' forward-word
bindkey -M viins '^[[1;5D' backward-word
bindkey -M viins '^?' backward-delete-char

function zle-line-init () {
  echoti smkx
}
function zle-line-finish () {
  echoti rmkx
}

if [ -n "${DISPLAY:-}" ]; then
  zle -N zle-line-init
  zle -N zle-line-finish
fi

# Edit current command in editor
autoload -z edit-command-line
zle -N edit-command-line
bindkey "^X^E" edit-command-line

# Colored man
man() {
  env LESS_TERMCAP_mb=$'\E[01;31m' \
    LESS_TERMCAP_md=$'\E[01;38;5;74m' \
    LESS_TERMCAP_me=$'\E[0m' \
    LESS_TERMCAP_se=$'\E[0m' \
    LESS_TERMCAP_so=$'\E[38;5;246m' \
    LESS_TERMCAP_ue=$'\E[0m' \
    LESS_TERMCAP_us=$'\E[04;38;5;146m' \
    man "$@"
}

# Color aliases
if [ -x /usr/bin/dircolors ]; then
  alias ls='ls --color=auto --group-directories-first'
  alias dir='dir --color=auto'
  alias vdir='vdir --color=auto'
  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
fi

# GNU ls aliases
# alias ll='ls -lFhX --time-style=long-iso'
# alias la='ls -A'

# LSDeluxe aliases
alias la='lsd -A'
alias ll='lsd -lFX'
alias lla='lsd -lFXA'
alias lsd='lsd -1'
alias l='lsd'

alias rm='rm -I'
alias ranger='. ranger'

alias tt='cd /tmp'
alias 44='cd /tmp/1-imgs'
alias pwf='sudo poweroff'
alias rbt='sudo reboot'
alias psu='ps -lFww --ppid 2 -p 2 --deselect'
alias cpptags='ctags -R --c++-kinds=+p --fields=+iaS --extra=+q --language-force=C++'

ei() {
  if file_path="$(/usr/bin/which --skip-functions --skip-alias "$1" 2>/dev/null)"; then
    nvim "$file_path"
  else
    echo "$1 not found"
  fi
}

edit-current-script() {
  ei "$(echo "${BUFFER}" | awk '{print $1}')"
}

zle -N edit-current-script
bindkey '^X^V' edit-current-script

rdp() {
  rdesktop "$1" -g 1920x1060 -u "$2" -z -0 -r clipboard:CLIPBOARD ${@:3}
}

jp() {
  for f in "$@"; do
    magick "${f}" "${f%.*}.jpg" && rm "${f}"
  done
}

jpk() {
  for f in "$@"; do
    magick "${f}" "${f%.*}.jpg"
  done
}

source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

ZLE_RPROMPT_INDENT=0
source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
source "$HOME/.p10k.zsh"

source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh
export FZF_COMPLETION_TRIGGER=''
bindkey '^I' "$fzf_default_completion"
export FZF_ALT_C_OPTS="--walker dir,follow"
export FZF_COMPLETION_OPTS="--header-first --header 'Keymap: Ctrl-O(rifle), Ctrl-U(doublecmd), Ctrl-E(vim), Ctrl-Y(copy path), Ctrl-H(copy absolute path)'
  --bind 'ctrl-o:execute(rifle {})+abort'
  --bind 'ctrl-u:execute-silent(doublecmd -C {} &)+abort'
  --bind 'ctrl-e:execute(vim {})+abort'
  --bind 'ctrl-y:execute-silent(echo -n {} | xsel -i -b)'
  --bind 'ctrl-h:execute-silent(echo -n \$(realpath -s {}) | xsel -i -b)'"
export FZF_CTRL_T_OPTS="${FZF_COMPLETION_OPTS}"

flc() {
  local cd_path
  cd_path=$(locate -i "$1" | fzf \
    --scheme=path \
    --height '40%' \
    --header-first --header 'Keymap: Enter(cd), Ctrl-O(rifle), Ctrl-U(doublecmd), Ctrl-E(vim), Ctrl-Y(copy path), Ctrl-H(copy absolute path)' \
    --bind 'ctrl-o:execute(rifle {})+abort' \
    --bind 'ctrl-u:execute-silent(doublecmd -C {} &)+abort' \
    --bind 'ctrl-e:execute(vim {})+abort' \
    --bind 'ctrl-y:execute-silent(echo -n {} | xsel -i -b)' \
    --bind 'ctrl-h:execute-silent(echo -n $(realpath -s {}) | xsel -i -b)')
  if [ -z "${cd_path}" ]; then
    return
  elif [ -d "${cd_path}" ]; then
    cd -- "${cd_path}" || return
  else
    cd -- "$(dirname "${cd_path}")" || return
  fi
}

[[ -f "$HOME/.zshrc_local" ]] && source "$HOME/.zshrc_local"

