LogLevel 0
LogDir "stdout"

SymbolsPreproc     "char"
SymbolsPreprocFile "symbols.dic"
SymbolsPreprocFile "emojis.dic"

AudioOutputMethod "pipewire"
AddModule         "piper-tts" "sd_generic" "piper-tts.conf"
DefaultModule     "piper-tts"
