[background]
path = "/usr/share/backgrounds/greeter.jpg"
fit = "Fill"

[GTK]
application_prefer_dark_theme = true
cursor_theme_name = "Future-Cyan"
font_name = "Cantarell 11"
icon_theme_name = "Flat-Remix-Blue-Dark"
theme_name = "Flat-Remix-GTK-Blue-Darkest"

[commands]
reboot = [ "systemctl", "reboot" ]
poweroff = [ "systemctl", "poweroff" ]

[appearance]
greeting_msg = "Welcome"

[widget.clock]
format = "%A %d %B %Y %H:%M:%S"
resolution = "500ms"
